if __name__ == '__main__':
    try:
        num = int(input("Digite um num: "))
        
    except Exception as e:
        print ("Ocorreu um erro ao receber informações")
        